In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df=sns.load_dataset('iris')

In [ ]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x=df.drop('species',axis=1)
y=df['species']

In [ ]:
x

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [ ]:
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.33, random_state=42)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
model_knn = KNeighborsClassifier(n_neighbors=13)

In [ ]:
model_knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [ ]:
model_knn.score(x_test,y_test)

1.0

In [ ]:
from sklearn.svm import SVC

In [ ]:
model_svm=SVC(C=10,kernel='linear',gamma='auto')

In [ ]:
model_svm.fit(x_train,y_train)

SVC(C=10, gamma='auto', kernel='linear')

In [ ]:
model_svm.score(x_test,y_test)

1.0

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
classifier=GridSearchCV(model_svm,{
    'C':[1,10,20,30],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False)

In [ ]:
classifier.fit(x,y)

GridSearchCV(cv=5, estimator=SVC(C=10, gamma='auto', kernel='linear'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [ ]:
classifier.cv_results_

{'mean_fit_time': array([0.00264158, 0.00269275, 0.00387678, 0.00288067, 0.00278425,
        0.00308681, 0.00277896, 0.00242567]),
 'std_fit_time': array([0.00041602, 0.00072061, 0.00075341, 0.00028131, 0.00020288,
        0.00067287, 0.00035797, 0.00011252]),
 'mean_score_time': array([0.00212588, 0.0017797 , 0.00294218, 0.00232377, 0.0020102 ,
        0.00227232, 0.00236645, 0.00183554]),
 'std_score_time': array([4.73278994e-04, 9.14069097e-05, 3.45067999e-04, 3.78586681e-04,
        5.50598480e-05, 5.34683321e-04, 6.87450272e-04, 1.08054435e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [ ]:
result=pd.DataFrame(classifier.cv_results_)

In [ ]:
result

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002642,0.000416,0.002126,0.000473,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.002693,0.000721,0.001780,0.000091,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.003877,0.000753,0.002942,0.000345,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.002881,0.000281,0.002324,0.000379,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.002784,0.000203,0.002010,0.000055,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.003087,0.000673,0.002272,0.000535,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.002779,0.000358,0.002366,0.000687,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.002426,0.000113,0.001836,0.000108,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [ ]:
result[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
classifier_r=RandomizedSearchCV((model_svm),{
    'C':[1,10,20,30],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False,n_iter=4)

In [ ]:
classifier_r.fit(x,y)

RandomizedSearchCV(cv=5, estimator=SVC(C=10, gamma='auto', kernel='linear'),
                   n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [ ]:
results = pd.DataFrame(classifier_r.cv_results_)
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       10          rbf         0.980000
1       10       linear         0.973333
2       30       linear         0.960000
3       20          rbf         0.966667