In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
labels=['a','b','c']
my_list=[10,20,30]
arr=np.array([10,20,30])
d={1:10,2:20,3:30}

In [ ]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

data frame

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data={
    'Name':['john','tanaya','anna','linda'],
    'Age':[28,34,27,45],
    'City':['new york','paris','berlin','london'],
    'Salary':[65000,70000,62000,85000]
}
df=pd.DataFrame(data)

In [ ]:
# data_list=[
#     ['john','tanaya','anna','linda'],
#     [28,34,27,45],
#     ['new york','paris','berlin','london'],
#     [65000,70000,62000,85000]
# ]
# df2=pd.DataFrame(data_list)
# columns=["Name","Age","City","Salary"]
# df2=pd.DataFrame(data_list,columns= columns)

In [ ]:
df

     Name  Age      City  Salary
0    john   28  new york   65000
1  tanaya   34     paris   70000
2    anna   27    berlin   62000
3   linda   45    london   85000

In [ ]:
df[['Name','City']]

     Name      City
0    john  new york
1  tanaya     paris
2    anna    berlin
3   linda    london

In [ ]:
df["Designation"]=["doctor","eng.","it","farma"]

In [ ]:
df

     Name  Age      City  Salary Designation
0    john   28  new york   65000      doctor
1  tanaya   34     paris   70000        eng.
2    anna   27    berlin   62000          it
3   linda   45    london   85000       farma

In [ ]:
df.drop("Designation",axis=1,inplace=True)

In [ ]:
df

     Name  Age      City  Salary
0    john   28  new york   65000
1  tanaya   34     paris   70000
2    anna   27    berlin   62000
3   linda   45    london   85000

In [ ]:
df.loc[[0,1]]

     Name  Age      City  Salary
0    john   28  new york   65000
1  tanaya   34     paris   70000

In [ ]:
df.iloc[3]

Name       linda
Age           45
City      london
Salary     85000
Name: 3, dtype: object

In [ ]:
df.loc[[0,1]][["City","Salary"]]

       City  Salary
0  new york   65000
1     paris   70000

In [ ]:
df.loc[[2,3]][["Name","Age"]]

    Name  Age
2   anna   27
3  linda   45

In [ ]:
df

     Name  Age      City  Salary
0    john   28  new york   65000
1  tanaya   34     paris   70000
2    anna   27    berlin   62000
3   linda   45    london   85000

In [ ]:
#above 30 ages
df[df["Age"]>30]

     Name  Age    City  Salary
1  tanaya   34   paris   70000
3   linda   45  london   85000

In [ ]:
#above 30 ages and city are paris
df[(df["Age"]>30) & (df["City"]=="paris")]

     Name  Age   City  Salary
1  tanaya   34  paris   70000

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data={
    'A':[1,2,np.nan,4,5],
    'B':[1,2,3,4,5],
    'C':[1,2,3,np.nan,np.nan],
    'D':[1,np.nan,np.nan,np.nan,5]
}
fd=pd.DataFrame(data)

In [ ]:
fd

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
fd.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [ ]:
fd.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [ ]:
fd.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [ ]:
fd

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
fd.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [ ]:
fd.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [ ]:
fd.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [ ]:
values={'A':0,'B':100,'C':200,'D':300}
fd.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  300.0
2  0.0  3    3.0  300.0
3  4.0  4  200.0  300.0
4  5.0  5  200.0    5.0

In [ ]:
fd.fillna(fd.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0